### ISSUE TITLE
Release preparation

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/launch-kit#12]
Release preparation

- [x] update main readme
- [x] update workflow diagram in sketch @Aha203 
- [x] add readme to distribution repo
- [x] add readme to gentxs repo
- [x] add gentxs repo with .gitkeep to data repo in gen_txs
- [x] add readme to genesis generator tool 
- [x] remove run.sh script at genesis generator tool
- [x] cleanup params repo readme
- [x] add readmde to urbit gift tool
- [x] add readme to rewards calculator
- [x] add readme to cyberlinks exporter tool

**Comment by mastercyb** [comment]
State? As far as I know the release is done.
